name: Bump version and publish package

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v2.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        package-json: './projects/redyform/package.json'

  publish-gpr:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm install
      - run: npm run ng build redyform -- --prod
      - run: npm publish
        working-directory: ./dist/redyform
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
